// Package report formats flight data into human-readable outputs: Markdown
// briefings and aviation-themed PDF post-flight reports.
package report

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/askrejans/downwash/internal/telemetry"
)

// Markdown writes a post-flight briefing as a Markdown file to outputPath.
// videoName is typically the basename of the source MP4 file. codec is the
// detected or transcoded video codec string (e.g. "hevc", "h264").
func Markdown(stats telemetry.FlightStats, videoName, codec, outputPath string) error {
	sb := new(strings.Builder)

	sb.WriteString("# Post-Flight Briefing\n\n")
	sb.WriteString(fmt.Sprintf("**Video:** `%s`\n\n", videoName))
	sb.WriteString(fmt.Sprintf("*Generated by [downwash](https://github.com/askrejans/downwash) on %s*\n\n",
		time.Now().UTC().Format("2006-01-02 15:04 UTC")))

	sb.WriteString("---\n\n")

	// ── Flight overview ──────────────────────────────────────────────────────
	sb.WriteString("## Flight Overview\n\n")
	sb.WriteString("| Field | Value |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString(fmt.Sprintf("| Duration | %s |\n", formatDuration(stats.Duration)))
	sb.WriteString(fmt.Sprintf("| Frame count | %d |\n", stats.FrameCount))
	sb.WriteString(fmt.Sprintf("| GPS points | %d |\n", stats.GPSPointCount))

	if !stats.StartTime.IsZero() {
		sb.WriteString(fmt.Sprintf("| Start time (UTC) | %s |\n", stats.StartTime.UTC().Format("2006-01-02 15:04:05")))
	}
	if !stats.EndTime.IsZero() {
		sb.WriteString(fmt.Sprintf("| End time (UTC) | %s |\n", stats.EndTime.UTC().Format("2006-01-02 15:04:05")))
	}
	sb.WriteString("\n")

	// ── GPS ──────────────────────────────────────────────────────────────────
	sb.WriteString("## GPS\n\n")
	sb.WriteString("| Field | Value |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString(fmt.Sprintf("| Start position | %.6f°, %.6f° |\n", stats.StartLat, stats.StartLon))
	sb.WriteString(fmt.Sprintf("| End position | %.6f°, %.6f° |\n", stats.EndLat, stats.EndLon))
	sb.WriteString(fmt.Sprintf("| Total distance | %.0f m (%.2f km) |\n", stats.DistanceM, stats.DistanceM/1000))
	sb.WriteString("\n")

	// ── Altitude ─────────────────────────────────────────────────────────────
	sb.WriteString("## Altitude\n\n")
	sb.WriteString("| Field | Value |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString(fmt.Sprintf("| Max altitude ASL | %.1f m |\n", stats.MaxAltASL))
	sb.WriteString(fmt.Sprintf("| Min altitude ASL | %.1f m |\n", stats.MinAltASL))
	sb.WriteString(fmt.Sprintf("| Max altitude AGL | %.1f m |\n", stats.MaxAltAGL))
	sb.WriteString(fmt.Sprintf("| Min altitude AGL | %.1f m |\n", stats.MinAltAGL))
	sb.WriteString("\n")

	// ── Speed ────────────────────────────────────────────────────────────────
	sb.WriteString("## Speed\n\n")
	sb.WriteString("| Field | Value |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString(fmt.Sprintf("| Max speed | %.1f m/s (%.1f km/h) |\n",
		stats.MaxSpeedMS, stats.MaxSpeedMS*3.6))
	sb.WriteString(fmt.Sprintf("| Average speed | %.1f m/s (%.1f km/h) |\n",
		stats.AvgSpeedMS, stats.AvgSpeedMS*3.6))
	sb.WriteString("\n")

	// ── Camera settings ──────────────────────────────────────────────────────
	sb.WriteString("## Camera Settings (first frame)\n\n")
	sb.WriteString("| Field | Value |\n")
	sb.WriteString("|---|---|\n")
	if codec != "" {
		sb.WriteString(fmt.Sprintf("| Codec | %s |\n", strings.ToUpper(codec)))
	}
	if stats.ISO > 0 {
		sb.WriteString(fmt.Sprintf("| ISO | %d |\n", stats.ISO))
	}
	if stats.ShutterSpeed != "" {
		sb.WriteString(fmt.Sprintf("| Shutter speed | %s |\n", stats.ShutterSpeed))
	}
	if stats.FNumber > 0 {
		sb.WriteString(fmt.Sprintf("| f-number | f/%.1f |\n", stats.FNumber))
	}
	if stats.ColorTemp > 0 {
		sb.WriteString(fmt.Sprintf("| Color temperature | %d K |\n", stats.ColorTemp))
	}
	sb.WriteString("\n")

	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by downwash — DJI post-flight analysis toolkit*\n")

	return os.WriteFile(outputPath, []byte(sb.String()), 0o644)
}

// formatDuration formats a time.Duration as "3m 12s".
func formatDuration(d time.Duration) string {
	d = d.Round(time.Second)
	h := int(d.Hours())
	m := int(d.Minutes()) % 60
	s := int(d.Seconds()) % 60
	if h > 0 {
		return fmt.Sprintf("%dh %dm %ds", h, m, s)
	}
	if m > 0 {
		return fmt.Sprintf("%dm %ds", m, s)
	}
	return fmt.Sprintf("%ds", s)
}
